[package]
name = "burlap"
version = "1.1.1"
edition = "2021"

[dependencies]
# For history file
home = "0.5.4"
# For values
impl_ops = "0.1.1"
# For speed
rustc-hash = "1.1.0"
# For lists
indexmap = "1.9.2"
# For REPL
rustyline = "10.1.0"
# For lexing
logos = "0.13.0"
# For C ffi
libc = "0.2.142"
