[package]
name = "burlap"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "burlap"
path = "rust/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.4"
impl_ops = "0.1.1"
rustyline = "10.1.0"
