[package]
name = "burlap"
version = "1.0.0"
edition = "2021"

[dependencies]
# For history file
home = "0.5.4"
# For values
impl_ops = "0.1.1"
# For lists
indexmap = "1.9.2"
# For REPL
rustyline = "10.1.0"
